name: main

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message. What changes were made?"
        required: false
        default: "Updated Figma"
      version:
        description: "Which version of the Figma document to use?"
        required: false
        default: "" # Will use latest if not set
  push:
    branches:
      - "main"

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci --ignore-scripts --force

      - name: Run Figmagic and use latest Figma data
        id: figma-latest
        if: ${{ !github.event.inputs.version }}
        run: rm -rf src/tokens && npx figmagic --token ${{ secrets.FIGMA_TOKEN }} --url ${{ secrets.FIGMA_URL }}

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy "src" --project-name="design-tokens-demo"
